const MIN_DATE = new Date('2025-08-01T00:00:00');
const MAX_DATE = new Date('2027-12-31T23:59:59');
const STORAGE_KEY = 'calendar_v3';
const SCROLL_CONTAINER = document.getElementById('scrollContainer');
const DAY_TMPL = document.getElementById('dayTemplate');
function ymd(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmtLong(d){return d.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})}
function loadAll(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}}
function saveAll(m){localStorage.setItem(STORAGE_KEY,JSON.stringify(m))}
function getDayData(k){const a=loadAll();return a[k]||{tasks:["","",""],notes:""}}
function setDayData(k,d){const a=loadAll();a[k]=d;saveAll(a)}
function rewardSound(){const ctx=new (window.AudioContext||window.webkitAudioContext)();const now=ctx.currentTime;[523.25,659.25,783.99].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(f,now+i*0.1);g.gain.setValueAtTime(0.05,now+i*0.1);g.gain.exponentialRampToValueAtTime(0.0001,now+i*0.1+0.3);o.connect(g).connect(ctx.destination);o.start(now+i*0.1);o.stop(now+i*0.1+0.3)})}
function createDay(d){if(d<MIN_DATE||d>MAX_DATE)return null;const k=ymd(d);const node=DAY_TMPL.content.firstElementChild.cloneNode(true);node.dataset.date=k;node.querySelector('.day-title').textContent=fmtLong(d);const data=getDayData(k);node.querySelector('.notes-display').textContent=data.notes||'—';['t1','t2','t3'].forEach((c,i)=>node.querySelector('.'+c).textContent=data.tasks[i]||`Task ${i+1}: —`);node.querySelectorAll('.task-input').forEach((inp,i)=>inp.value=data.tasks[i]||'');node.querySelector('.notes-input').value=data.notes||'';node.querySelector('.day-header').addEventListener('click',()=>{document.querySelectorAll('.day.expanded').forEach(e=>{if(e!==node)e.classList.remove('expanded')});node.classList.toggle('expanded')});node.querySelector('.collapse-btn').addEventListener('click',e=>{e.stopPropagation();node.classList.remove('expanded')});node.querySelector('.save-btn').addEventListener('click',e=>{e.stopPropagation();const t=[...node.querySelectorAll('.task-input')].map(i=>i.value.trim()),n=node.querySelector('.notes-input').value;setDayData(k,{tasks:t,notes:n});node.querySelector('.notes-display').textContent=n||'—';['t1','t2','t3'].forEach((c,i)=>node.querySelector('.'+c).textContent=t[i]||`Task ${i+1}: —`);rewardSound()});return node}
function renderInitial(){let today=new Date();today.setHours(0,0,0,0);if(today<MIN_DATE)today=new Date(MIN_DATE);if(today>MAX_DATE)today=new Date(MAX_DATE);const before=Math.min(30,Math.floor((today-MIN_DATE)/(86400000)));const after=120;for(let i=before;i>=1;i--){const d=new Date(today);d.setDate(d.getDate()-i);const el=createDay(d);if(el)SCROLL_CONTAINER.appendChild(el)}for(let i=0;i<=after;i++){const d=new Date(today);d.setDate(d.getDate()+i);const el=createDay(d);if(el)SCROLL_CONTAINER.appendChild(el)}}renderInitial();